/* Mobile-first expansion: this registry is the single source for internal Learn and Tools route copy, contextual links and route-level SEO data. */
export type Topic = { slug: string; label: string; title: string; description: string; accent: "orange" | "mint" | "saffron" | "ink" };
export type Article = { slug: string; topic: string; title: string; description: string; readTime: string; visual: "salary" | "upi" | "rent" | "goa" | "home" | "library"; takeaway: string; sections: { title: string; paragraphs: string[] }[]; tool?: { label: string; href: string } };
export type ToolItem = { slug: string; title: string; eyebrow: string; description: string; visual: "sip" | "emi" | "goa"; query: string; learnSlug: string };

export const topics: Topic[] = [
  { slug: "start-here", label: "Start here", title: "Start with the month you have.", description: "A simpler way to see what comes in, what is due and what you want to keep moving.", accent: "orange" },
  { slug: "salary-planning", label: "Salary", title: "Give your salary a few clear jobs.", description: "Make room for bills, home, a little buffer and plans that matter to you.", accent: "saffron" },
  { slug: "upi-and-spending", label: "UPI week", title: "Small spends need some context.", description: "A calm way to look at the fast payments that make up an ordinary week.", accent: "mint" },
  { slug: "home-money", label: "Home money", title: "Share home costs, not every detail.", description: "Keep the selected things that matter to a home visible without mixing personal money.", accent: "ink" },
  { slug: "goals-and-saving", label: "Goals", title: "Keep the plan in the picture.", description: "A goal does not need to fight with every practical thing due this month.", accent: "orange" },
  { slug: "tax-and-long-term", label: "Long-term", title: "Long-term words, made simpler.", description: "Plain-English starting points for terms you may hear at work or at home.", accent: "saffron" },
];

export const tools: ToolItem[] = [
  { slug: "sip-calculator", title: "SIP Calculator", eyebrow: "Monthly plan", description: "Try a monthly amount, a return assumption and a time frame. See the estimate in one view.", visual: "sip", query: "SIP calculator India", learnSlug: "salary-day-is-not-spending-day" },
  { slug: "emi-calculator", title: "EMI Calculator", eyebrow: "Loan plan", description: "Try a loan amount, rate and tenure. See the monthly amount and overall cost clearly.", visual: "emi", query: "EMI calculator India", learnSlug: "rent-bills-cards-what-to-see-first" },
  { slug: "goa-goal-calculator", title: "Goa Goal Calculator", eyebrow: "Trip plan", description: "Put a Goa plan on the table. See what may be left to save every month.", visual: "goa", query: "travel goal calculator India", learnSlug: "goa-fund-without-guilt" },
];

export const articles: Article[] = [
  { slug: "salary-day-is-not-spending-day", topic: "salary-planning", title: "Salary day is not a spending day. Try these four jobs first.", description: "A simple way to give salary, bills, buffer and a personal plan some space before the month gets busy.", readTime: "4 min read", visual: "salary", takeaway: "The point is not to control every rupee. It is to make the important things visible before they surprise you.", tool: { label: "Try the Goa Goal Calculator", href: "/learn/tools/goa-goal-calculator" }, sections: [{ title: "Start with what cannot wait", paragraphs: ["Rent, a bill or a home expense does not need a complicated category. It just needs a clear place in your view.", "A simple first step is to name the things that are already spoken for this month. That makes the rest easier to see."] }, { title: "Leave room for the plan you care about", paragraphs: ["A Goa plan, a course or a small buffer can sit beside the practical stuff. It does not need to wait until every month is perfect.", "Small repeatable choices usually feel easier than one dramatic money rule."] }] },
  { slug: "upi-weekly-check-in", topic: "upi-and-spending", title: "UPI all week? A five-minute Friday check-in can help.", description: "A no-shame way to look back at the quick payments that are easy to forget by Sunday.", readTime: "3 min read", visual: "upi", takeaway: "The goal is context, not guilt. A short weekly check can make small spends easier to remember.", sections: [{ title: "Quick is good. Invisible is not always helpful.", paragraphs: ["UPI makes ordinary things easy. A cab, lunch, chai, a small gift or groceries can happen before you have had time to think about them.", "That does not make the payment bad. It simply means your money story can become scattered."] }, { title: "Use one small check-in", paragraphs: ["Pick a moment that already belongs to you, such as Friday evening or Sunday morning. Look at the week and name the payments you would otherwise forget.", "You are not looking for a perfect score. You are making next week less surprising."] }] },
  { slug: "rent-bills-cards-what-to-see-first", topic: "start-here", title: "Rent, bills, cards. What should be visible first?", description: "A plain starter order for the commitments that can feel noisy when they are spread across different places.", readTime: "4 min read", visual: "rent", takeaway: "Start with what has a date. The month becomes easier to handle when due things are not hidden.", tool: { label: "Try the EMI Calculator", href: "/learn/tools/emi-calculator" }, sections: [{ title: "Look for dates before categories", paragraphs: ["When you are deciding what to see first, dates are often more useful than a long list of labels. A due date tells you which part of the month needs attention.", "Rent, a card bill and a regular repayment may all live in different places. Bringing the dates together is a useful first move."] }, { title: "Make the next thing obvious", paragraphs: ["A money view works best when it answers one clear question: what needs attention next?", "You can add more detail later. Start with the commitment that would be most annoying to miss."] }] },
  { slug: "goa-fund-without-guilt", topic: "goals-and-saving", title: "Goa ka plan. A simple way to keep it visible.", description: "A travel plan can live beside rent, bills and everyday spending without becoming a source of guilt.", readTime: "3 min read", visual: "goa", takeaway: "A goal becomes easier to keep when it has a visible place next to the rest of the month.", tool: { label: "Try the Goa Goal Calculator", href: "/learn/tools/goa-goal-calculator" }, sections: [{ title: "Do not hide the fun plan", paragraphs: ["A short trip, a concert or a course can feel less serious than a bill. But it may still be a real plan for you.", "Keeping it visible does not promise that it will happen. It simply lets you make the choice with the full month in mind."] }, { title: "Make the next amount small enough to repeat", paragraphs: ["A number that works every month can feel more useful than a large target that makes you switch off.", "Try a simple estimate, then adjust it when the timeline or the plan changes."] }] },
  { slug: "home-money-without-mix-up", topic: "home-money", title: "Home money without the mix-up.", description: "How selected home costs can stay visible while personal money remains personal.", readTime: "4 min read", visual: "home", takeaway: "Shared does not have to mean everything. Clear boundaries can make home conversations easier.", sections: [{ title: "Name what is truly shared", paragraphs: ["Rent, groceries, a utility bill or a home repair may matter to more than one person. It can help to give those things a shared view.", "Personal purchases and personal plans do not need to become part of that view unless you want them to."] }, { title: "Keep the conversation simple", paragraphs: ["A shared money conversation does not need to start with every transaction. Start with the one cost that affects the home this week.", "The point is clarity between people, not surveillance."] }] },
  { slug: "epf-ppf-nps-basics", topic: "tax-and-long-term", title: "EPF, PPF and NPS. What each is meant for.", description: "A plain-English introduction to three long-term terms. General education, not a personal recommendation.", readTime: "5 min read", visual: "library", takeaway: "Long-term words can be understood one at a time. A starting point is more useful than a rushed decision.", sections: [{ title: "Start with the full name and the purpose", paragraphs: ["These terms often come up when you start a job, talk about long-term saving or look at tax-related paperwork. Each has a different structure and set of rules.", "Before taking any action, use current official sources or a qualified professional for details that apply to you."] }, { title: "Do not turn a simple explainer into a decision", paragraphs: ["A short guide can help you understand the words and frame better questions. It cannot tell you what is right for your income, goals or tax situation.", "If you choose to act, check the latest official rules and consider getting advice suited to your own situation."] }] },
];

export const getArticle = (slug: string) => articles.find((article) => article.slug === slug);
export const getTopic = (slug: string) => topics.find((topic) => topic.slug === slug);
export const getTool = (slug: string) => tools.find((tool) => tool.slug === slug);
