/* Living Ledger modernisation: a short, lively Indian money story makes Kubear feel useful in seconds, then explains control in simple words. */
import { ArrowRight, ArrowUpRight, CircleHelp, Eye, Landmark, LockKeyhole, MoveRight, ShieldCheck, UsersRound, WalletCards } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { LedgerEvidence } from "@/components/LedgerEvidence";
import { LedgerScene } from "@/components/LedgerScene";
import { PageMeta } from "@/components/PageMeta";
import { SiteLayout } from "@/components/SiteChrome";

const fragments = ["Salary", "UPI", "Card bill", "SIP", "Rent", "Subscriptions", "Home expenses"];
const outcomes = [
  { icon: Landmark, number: "01", title: "See what you really have", text: "Not just your bank balance. See it with the bills and payments coming next." },
  { icon: WalletCards, number: "02", title: "Know what you can spend", text: "See what is already booked, so a normal spending choice feels simpler." },
  { icon: CircleHelp, number: "03", title: "Ask in simple words", text: "Ask the money question in your head. Kubear helps put the numbers in context." },
];
const faqs = [
  ["What is Kubear?", "Kubear is a personal finance assistant. It helps you see the money information you choose to connect in one place."],
  ["Is it an expense tracker or an investing app?", "Not really. Kubear is built to help you see the full picture around your money. Your bank, UPI, investing or spending app can still do their own job."],
  ["Can Kubear move my money?", "No. Kubear’s public information says it is read-only. It can show your picture, but it cannot move your money."],
  ["Can I choose what Kubear sees?", "Yes. Kubear’s current public information says you choose what to connect. You can also disconnect or delete your data."],
  ["Is Kubear free?", "Kubear’s current website says it is free in beta. Check the latest pricing before relying on this."],
];

export default function Home() {
  return <SiteLayout><PageMeta title="Kubear | See your money in one view" description="Kubear brings the money information you choose to connect into one clear, read-only view, so everyday money decisions feel simpler." />
    <section className="paper-grid modern-hero relative overflow-hidden px-5 pb-16 pt-12 sm:px-8 sm:pb-20 lg:px-12 lg:pb-28 lg:pt-20"><div className="hero-orbit hero-orbit-a" /><div className="hero-orbit hero-orbit-b" /><div className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-[0.78fr_1.22fr] lg:items-center lg:gap-12"><div className="relative z-10 max-w-2xl" data-reveal><p className="eyebrow text-[#C96632]"><span className="mr-2 inline-block size-2 rounded-full bg-[#C96632]" />Your money, clearly together</p><h1 className="display hero-title mt-6 text-[#102B28]">Your money is in many places. See it in one view.</h1><p className="lede mt-7">Salary comes in. UPI goes out. Your card bill is due. Your SIP is on. Kubear puts it together so you can make the next money call with more clarity.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a className="button button-primary" href="https://kubear.kuberos.in" target="_blank" rel="noreferrer">Join early access <ArrowUpRight className="size-4" /></a><a className="button button-secondary" href="#money-view">See how it works <ArrowRight className="size-4" /></a></div><p className="trust-line mt-5"><Eye className="size-4 text-[#C96632]" />Just see. No money moves from here.</p></div><div className="relative" data-reveal><div className="hero-label hero-label-left"><span>Step 1</span>Connect what matters</div><div className="hero-label hero-label-right"><span>Step 2</span>See the story</div><LedgerScene className="hero-ledger border border-[#102B28]/10 shadow-[0_28px_80px_rgba(16,43,40,0.13)]" /></div></div></section>
    <section className="border-y border-[#102B28]/10 bg-[#FEFCF7] px-5 py-4 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-x-6 gap-y-2 text-sm font-bold text-[#53625B]"><span className="eyebrow text-[#C96632]">Made for everyday Indian money</span><span>Salary · UPI · cards · SIPs · rent</span><span className="inline-flex items-center gap-2"><ShieldCheck className="size-4 text-[#4D7869]" />See only. Stay in control.</span></div></section>
    <section className="bg-[#102B28] px-5 py-20 text-[#FDF9F0] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.83fr_1.17fr] lg:items-center"><div data-reveal><p className="eyebrow text-[#E2BA66]">Does this sound familiar?</p><h2 className="section-title mt-5 text-white">Bank. UPI. Cards. SIPs. You are doing the maths in your head.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#CBD4CF]">Every app knows one thing. But when you are about to spend, save, split the rent or plan the month, you need to see how those things fit together.</p></div><div className="money-pieces" data-reveal><div className="piece-path" />{fragments.map((fragment, index) => <div className={`money-piece money-piece-${index}`} key={fragment}>{fragment}</div>)}<p>Good money apps do their job. Kubear helps you see the full picture.</p></div></div></section>
    <section id="money-view" className="paper-grid px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div data-reveal><p className="eyebrow text-[#C96632]">Aaj ka money view</p><h2 className="section-title mt-5">One quick check. A much clearer day.</h2><p className="mt-6 text-lg leading-8 text-[#53625B]">Kubear brings your chosen money information into one calm view. You can spot what came in, what is due and what may need your attention.</p><div className="mt-8 space-y-4">{["See your money, not just one balance", "Spot bills and payments due next", "Ask a straight question when you need it"].map((line) => <div className="flex items-center gap-3" key={line}><span className="grid size-6 place-items-center rounded-full bg-[#F6E6DD] text-xs font-extrabold text-[#C96632]">✓</span><span className="font-bold text-[#102B28]">{line}</span></div>)}</div></div><LedgerEvidence variant="today" /></div></section>
    <section className="px-5 pb-20 sm:px-8 lg:px-12 lg:pb-28"><div className="mx-auto max-w-[1280px]">{outcomes.map((outcome, index) => { const Icon = outcome.icon; return <article data-reveal className={`ledger-entry ${index === 1 ? "lg:ml-[10%]" : ""}`} key={outcome.title}><span className="ledger-entry-number">{outcome.number}</span><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#F6E6DD] text-[#C96632]"><Icon className="size-5" /></span><div><h3>{outcome.title}</h3><p>{outcome.text}</p></div><span className="ledger-entry-rule" /></article>; })}</div></section>
    <section className="mx-5 overflow-hidden rounded-[2rem] bg-[#E7DED0] sm:mx-8 lg:mx-12"><div className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-[1fr_0.95fr] lg:items-center"><LedgerEvidence variant="picture" /><div className="px-7 py-14 sm:px-10 lg:px-14" data-reveal><p className="eyebrow text-[#C96632]">The moment it clicks</p><h2 className="section-title mt-5">Your money should not feel like a puzzle.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#53625B]">Your salary, UPI spends, bills, SIPs and home costs are not separate stories. See them in one view and the next step feels less stressful.</p><div className="margin-note mt-7">The goal is not more data. It is one clear answer when you need it.</div><a href="/how-it-works" className="mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-[#102B28] hover:text-[#C96632]">See the simple flow <MoveRight className="size-4" /></a></div></div></section>
    <section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.88fr_1.12fr] lg:items-center"><div data-reveal><p className="eyebrow text-[#C96632]">Personal and home</p><h2 className="section-title mt-5">Home expenses together. Personal money stays personal.</h2><p className="mt-6 text-lg leading-8 text-[#53625B]">Rent, groceries and bills are easier when you see them together. Your personal savings and spending should still stay in your own view.</p><a href="/your-money-picture" className="button button-secondary mt-8">See your money view <ArrowRight className="size-4" /></a></div><div className="home-split" data-reveal><div className="home-slip home-slip-personal"><p className="eyebrow text-[#6E756C]">Personal</p><p>Your own money view</p><span /><span /><span /></div><div className="home-slip home-slip-shared"><p className="eyebrow text-[#E2BA66]">Home</p><p>The things you share</p><div><b>Rent</b><b>Groceries</b><b>Bills</b></div></div></div></div></section>
    <section className="bg-[#F4EFE4] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_1fr] lg:items-center"><LedgerEvidence variant="life" /><div data-reveal><p className="eyebrow text-[#C96632]">Money is part of real life</p><h2 className="section-title mt-5">A plan, a move, a family, a break. Money is there too.</h2><p className="mt-6 text-lg leading-8 text-[#53625B]">You are not making money choices in a vacuum. A clearer view gives you more room to focus on what the choice is really about.</p></div></div></section>
    <section className="bg-[#102B28] px-5 py-20 text-[#FDF9F0] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.86fr_1.14fr] lg:items-center"><div data-reveal><p className="eyebrow text-[#E2BA66]">Simple, clear control</p><h2 className="section-title mt-5 text-white">Your money. Your data. Your call.</h2><p className="mt-6 text-lg leading-8 text-[#CBD4CF]">Kubear is built to show the picture, not move your money. You choose what to connect and you should always know how to disconnect or delete it.</p><a href="/privacy-data" className="button button-light mt-8">See privacy details <ArrowRight className="size-4" /></a></div><div className="trust-ledger" data-reveal>{[[Eye,"Read-only","Just see your money picture. No money moves from Kubear."],[LockKeyhole,"Clear boundaries","Published policy says no banking password, UPI PIN or OTP collection."],[UsersRound,"Your choice","Choose what to connect. Disconnect when you want."],[ShieldCheck,"Easy to leave","Find the delete-account route without going through a maze."]].map(([Icon,title,text], index) => { const EntryIcon = Icon as typeof Eye; return <div className="trust-entry" key={String(title)}><span>0{index + 1}</span><EntryIcon className="size-5 text-[#E2BA66]" /><div><h3>{String(title)}</h3><p>{String(text)}</p></div></div>; })}</div></div></section>
    <section className="paper-grid px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.78fr_1.22fr]"><div data-reveal><p className="eyebrow text-[#C96632]">Quick answers</p><h2 className="section-title mt-5">What you may be wondering.</h2><p className="mt-5 leading-7 text-[#53625B]">The basics, in simple words.</p></div><Accordion type="single" collapsible className="rounded-[1.5rem] border border-[#102B28]/12 bg-[#FEFCF7] px-6 sm:px-8" data-reveal>{faqs.map(([question, answer], index) => <AccordionItem value={`faq-${index}`} key={question}><AccordionTrigger className="py-6 text-base font-extrabold text-[#102B28] no-underline hover:no-underline sm:text-lg">{question}</AccordionTrigger><AccordionContent className="max-w-2xl pb-6 text-base leading-7 text-[#53625B]">{answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="px-5 pb-20 sm:px-8 lg:px-12 lg:pb-28"><div className="final-ledger-cta mx-auto max-w-[1280px] overflow-hidden rounded-[2rem] px-7 py-14 sm:px-10 lg:px-16 lg:py-16"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between" data-reveal><div className="max-w-3xl"><p className="eyebrow text-[#E2BA66]">Early access · India</p><h2 className="mt-5 font-serif text-5xl leading-[0.94] tracking-[-0.06em] text-[#fffaf4] sm:text-6xl">Less checking. More clarity.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#CBD4CF]">Join early access and help shape a calmer way to handle everyday money.</p></div><a className="button button-light shrink-0" href="https://kubear.kuberos.in" target="_blank" rel="noreferrer">Join early access <ArrowUpRight className="size-4" /></a></div></div></section>
  </SiteLayout>;
}
