/* Week Comes Together: the homepage is a bold, Indian money-week story with real Kubear screens, gentle Hinglish and one clear action after each visual payoff. */
import { ArrowRight, ArrowUpRight, Check, Eye, LockKeyhole, ScanLine, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { PageMeta } from "@/components/PageMeta";
import { SiteLayout } from "@/components/SiteChrome";
import { APP_URL, GoalMoment, HomeMoneyToggle, PLAY_URL, ProductPoster, SalaryRibbon, WeekAssembly } from "@/components/WeekStory";

const faqs = [
  ["What is Kubear?", "Kubear is a personal and household money manager for adults in India. It helps you record money details, plan monthly needs, keep bills and goals visible, and see what remains after planned commitments."],
  ["Can Kubear move my money?", "No. Kubear does not hold or move money. It helps you organise and understand the information you add or choose to connect."],
  ["Can I use it for home money?", "Yes. Kubear’s Money Spaces are designed to help a household coordinate selected shared entries while personal entries stay separate."],
  ["Is this financial advice?", "No. Kubear is not a bank, payment service, investment adviser, tax service or legal adviser. It does not provide regulated financial advice."],
];

export default function Home() {
  return <SiteLayout><PageMeta title="Kubear | Your money week, in one place" description="See salary, UPI spending, bills, goals and home money together with Kubear. It does not hold or move your money." />
    <section className="week-hero px-5 pb-10 pt-12 sm:px-8 sm:pb-14 lg:px-12 lg:pb-20 lg:pt-18"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[0.82fr_1.18fr] lg:items-center lg:gap-14"><div className="week-hero-copy" data-reveal><p className="week-kicker"><span />Your money week, in one place</p><h1 className="week-display">Salary in.<br />Bills due.<br /><em>UPI everywhere.</em></h1><p className="week-lede">Kubear helps you see income, spending, bills, goals and home money together. Dekho kya bacha hai. Dekho kya next hai.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a className="button button-orange app-desktop" href={APP_URL}>Open Kubear <ArrowUpRight className="size-4" /></a><a className="button button-orange app-mobile" href={PLAY_URL} target="_blank" rel="noreferrer">Get it on Google Play <ArrowUpRight className="size-4" /></a><a className="button button-secondary app-desktop" href={PLAY_URL} target="_blank" rel="noreferrer">Get the Android app <ArrowUpRight className="size-4" /></a><a className="button button-secondary app-mobile" href={APP_URL}>Open web app <ArrowRight className="size-4" /></a></div><p className="week-trust"><Eye className="size-4" />Just see. Kubear does not hold or move your money.</p></div><div className="relative" data-reveal><WeekAssembly /></div></div></section>
    <section className="week-rail"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-3 px-5 py-4 sm:px-8 lg:px-12"><span>MON · SALARY</span><span>TUE TO THU · UPI</span><span>FRI · CARD BILL</span><span>SUN · GOA FUND</span><span className="week-rail-emphasis"><ShieldCheck className="size-4" />SEE IT. PLAN IT.</span></div></section>
    <section id="money-view" className="week-intro bg-[#092B27] px-5 py-20 text-[#FFF4E6] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.83fr_1.17fr] lg:items-center"><div data-reveal><p className="week-kicker text-[#FFB18E]"><span />One week. One full view.</p><h2 className="week-section-title text-white">All those small money things? <em>They add up.</em></h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#D8E2DC]">A UPI payment can feel tiny. A card bill, rent and plan for Goa can feel far away. Together, they decide what your week actually looks like.</p><a href="#aaj" className="week-text-link mt-8">See the Aaj view <ArrowRight className="size-4" /></a></div><div className="week-fragment-field" data-reveal><span className="fragment-label fragment-upi">UPI spend</span><span className="fragment-label fragment-rent">Rent</span><span className="fragment-label fragment-goal">Goa fund</span><span className="fragment-label fragment-card">Card bill</span><span className="fragment-label fragment-salary">Salary</span><div className="fragment-centre"><ScanLine className="size-5" /><b>One clear view</b><small>Not more maths in your head</small></div></div></div></section>
    <section id="aaj" className="aaj-scene px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div data-reveal><p className="week-kicker"><span />Aaj ka view</p><h2 className="week-section-title">Dekho kya bacha hai. <em>Dekho kya next hai.</em></h2><p className="week-lede mt-6">See the parts of your money picture in one place, so the next decision has more context. No hunting through different apps first.</p><div className="week-checks mt-8"><p><Check className="size-4" />Keep income, bills and goals close</p><p><Check className="size-4" />See what needs attention next</p><p><Check className="size-4" />Ask a simple question when you need to</p></div><a href={APP_URL} className="button button-dark mt-8">Open Kubear <ArrowUpRight className="size-4" /></a></div><div className="aaj-poster-wrap" data-reveal><ProductPoster type="today" /><div className="aaj-note aaj-note-one">Friday<br /><b>Card bill</b></div><div className="aaj-note aaj-note-two">This week<br /><b>SIP check</b></div></div></div></section>
    <section className="salary-scene px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[1.08fr_0.92fr] lg:items-center"><div className="order-2 lg:order-1" data-reveal><SalaryRibbon /></div><div className="order-1 lg:order-2" data-reveal><p className="week-kicker"><span />Make salary day last</p><h2 className="week-section-title">Plan your salary <em>before it disappears.</em></h2><p className="week-lede mt-6">Start with the things that already have a job. Monthly needs. Bills. A little buffer. Then the plan for something good, like that Goa trip.</p><div className="week-margin-note mt-7">A plan is not a punishment. It is just a clearer yes or no.</div><a className="week-text-link mt-8" href={APP_URL}>Plan with Kubear <ArrowRight className="size-4" /></a></div></div></section>
    <section className="home-scene bg-[#F0E0C9] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.88fr_1.12fr] lg:items-center"><div data-reveal><p className="week-kicker"><span />Home and personal</p><h2 className="week-section-title">Ghar ka money together. <em>Personal money stays personal.</em></h2><p className="week-lede mt-6">Shared rent, groceries and bills are easier to handle when everyone sees the right thing. Your own money view stays yours.</p><a href="/your-money-picture" className="button button-dark mt-8">See your money view <ArrowRight className="size-4" /></a></div><div data-reveal><HomeMoneyToggle /></div></div></section>
    <section className="goal-scene px-5 py-20 text-white sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[1.07fr_0.93fr] lg:items-center"><div data-reveal><GoalMoment /></div><div data-reveal><p className="week-kicker text-[#FFE7A4]"><span />Goals in real life</p><h2 className="week-section-title text-white">Bills close. <em>Goa fund moving.</em></h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#FFF4E6]">A goal needs a place beside the stuff that has to be paid. Keep the plan in sight, even after a busy week.</p><a className="button button-light mt-8" href={PLAY_URL} target="_blank" rel="noreferrer">Get the Android app <ArrowUpRight className="size-4" /></a></div></div></section>
    <section className="trust-scene bg-[#092B27] px-5 py-20 text-[#FFF4E6] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.86fr_1.14fr] lg:items-center"><div data-reveal><p className="week-kicker text-[#FFB18E]"><span />Clear boundaries</p><h2 className="week-section-title text-white">Your money. Your data. <em>Clear rules.</em></h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#D8E2DC]">Kubear helps you organise what you choose to add or connect. It does not hold or move money. You should always know what is in your view and how to leave.</p><a href="/privacy-data" className="week-text-link mt-8">See privacy details <ArrowRight className="size-4" /></a></div><div className="trust-product" data-reveal><ProductPoster type="privacy" /><div className="trust-rule trust-rule-one"><LockKeyhole className="size-4" />No money movement</div><div className="trust-rule trust-rule-two"><UsersRound className="size-4" />Your choice</div></div></div></section>
    <section className="faq-scene px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.78fr_1.22fr]"><div data-reveal><p className="week-kicker"><span />Quick answers</p><h2 className="week-section-title">Simple questions. <em>Straight answers.</em></h2><p className="week-lede mt-5">The basics, without the finance lecture.</p></div><Accordion type="single" collapsible className="week-accordion" data-reveal>{faqs.map(([question, answer], index) => <AccordionItem value={`faq-${index}`} key={question}><AccordionTrigger className="py-6 text-left text-base font-extrabold text-[#14312E] no-underline hover:no-underline sm:text-lg">{question}</AccordionTrigger><AccordionContent className="max-w-2xl pb-6 text-base leading-7 text-[#53625B]">{answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="app-handoff px-5 pb-20 sm:px-8 lg:px-12 lg:pb-28"><div className="app-handoff-inner mx-auto grid max-w-[1280px] gap-10 overflow-hidden px-7 py-12 sm:px-10 lg:grid-cols-[1fr_0.92fr] lg:items-center lg:px-14 lg:py-16"><div data-reveal><p className="week-kicker text-[#FFB18E]"><span />When the week gets busy</p><h2 className="week-section-title text-white">Your money week, <em>easier to handle.</em></h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#D8E2DC]">Use Kubear on web or Android. Pick what works for you.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a className="button button-light" href={APP_URL}>Use the web app <ArrowUpRight className="size-4" /></a><a className="button button-outline-light" href={PLAY_URL} target="_blank" rel="noreferrer">Get it on Google Play <ArrowUpRight className="size-4" /></a></div></div><div className="handoff-device" data-reveal><img className="handoff-screen" src="/manus-storage/kubear-app-home-plan_b6b4876e.webp" alt="Kubear Android app screen" /><a className="handoff-qr" href={PLAY_URL} target="_blank" rel="noreferrer"><img src="/manus-storage/kubear-play-qr_41314e26.png" alt="QR code to download Kubear on Google Play" /><span>Scan for Android</span></a><div className="handoff-spark"><Sparkles className="size-5" /></div></div></div></section>
  </SiteLayout>;
}
