/* Living Ledger design: the homepage creates recognition through financial fragments, then resolves them into a calm, bounded personal picture. */
import { ArrowRight, ArrowUpRight, Check, CircleHelp, Eye, Landmark, LockKeyhole, MoveRight, Sparkles, UsersRound, WalletCards } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { LedgerEvidence } from "@/components/LedgerEvidence";
import { LedgerScene } from "@/components/LedgerScene";
import { PageMeta } from "@/components/PageMeta";
import { SiteLayout } from "@/components/SiteChrome";

const fragments = ["Salary", "UPI spends", "Card bill", "SIP", "Rent", "Insurance", "Subscriptions", "Shared home"];
const outcomes = [
  { icon: Landmark, title: "Know where you stand", text: "See a financial picture that is more useful than checking every app one by one." },
  { icon: WalletCards, title: "Know what is coming", text: "Keep upcoming bills, commitments and transactions in the same story as your current balance." },
  { icon: CircleHelp, title: "Ask the question behind the number", text: "Bring a plain-language question to the context you have already chosen to connect." },
];
const faqs = [
  ["What exactly is Kubear?", "Kubear’s current public materials describe it as a personal finance assistant that helps people understand the financial information they choose to connect. It is not a bank, broker, investment adviser or payment service."],
  ["Is Kubear an expense tracker or an investment app?", "Kubear is designed around the picture across everyday money information—not around replacing a specialist spending, banking or investment app. Its published materials describe timeline, context, daily briefing and question-answering uses."],
  ["Does Kubear move or invest my money?", "The published terms and product materials say Kubear is read-only and does not move money. It is not presented as a brokerage or payment service."],
  ["Why not just use Excel or another money app?", "A spreadsheet can calculate and specialist apps can handle their own job. Kubear’s role is to reduce the work of connecting the pieces around an everyday money decision. The best choice depends on how you manage your finances."],
  ["Can I control what Kubear can see?", "Current public materials say you choose what to connect and can disconnect or delete your information. Review the latest approved privacy policy before relying on any data-handling detail."],
  ["How much does Kubear cost?", "The current website states that Kubear is free while in beta. Pricing should be confirmed with the product owner before this statement is used on a public replacement site."],
];

export default function Home() {
  return <SiteLayout><PageMeta title="Kubear — Every money decision needs the whole picture" description="Kubear brings the financial information you choose to connect into one read-only picture, so the next decision takes less mental work." />
    <section className="paper-grid relative overflow-hidden px-5 pb-16 pt-12 sm:px-8 sm:pb-20 lg:px-12 lg:pb-28 lg:pt-20">
      <div className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-[0.78fr_1.22fr] lg:items-center lg:gap-12">
        <div className="relative z-10 max-w-2xl"><p className="eyebrow text-[#C96632]"><span className="mr-2 inline-block size-2 rounded-full bg-[#C96632]" />A read-only financial picture</p><h1 className="display mt-6 text-[#102B28]">Every money decision needs the whole picture.</h1><p className="lede mt-7">Kubear brings the accounts, bills, spending, investments and household commitments you choose to connect into one read-only picture—so the next decision takes less mental work.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a className="button button-primary" href="https://kubear.kuberos.in" target="_blank" rel="noreferrer">Join early access <ArrowUpRight className="size-4" /></a><a className="button button-secondary" href="#how-kubear-helps">See how it works <ArrowRight className="size-4" /></a></div><p className="mt-5 flex items-center gap-2 text-sm font-semibold text-[#53625B]"><Eye className="size-4 text-[#C96632]" />Read-only by design. Your money does not move through Kubear.</p></div>
        <div className="relative"><img src="/manus-storage/kubear-living-ledger-hero_0a5e8b15.png" alt="Abstract financial fragments converging into a composed ledger" className="absolute inset-0 h-full w-full rounded-[2rem] object-cover opacity-75 mix-blend-multiply" /><LedgerScene className="border border-[#102B28]/10 shadow-[0_28px_80px_rgba(16,43,40,0.13)]" /></div>
      </div>
    </section>
    <section className="border-y border-[#102B28]/10 bg-[#FEFCF7] px-5 py-5 sm:px-8 lg:px-12"><div className="mx-auto flex max-w-[1440px] flex-wrap items-center justify-between gap-x-6 gap-y-3 text-sm font-bold text-[#53625B]"><span className="eyebrow text-[#C96632]">Built around Indian money habits</span><span>UPI · cards · SIPs · bills · shared homes</span><span className="inline-flex items-center gap-2"><LockKeyhole className="size-4 text-[#4D7869]" />A control-first product story</span></div></section>
    <section className="bg-[#102B28] px-5 py-20 text-[#FDF9F0] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.83fr_1.17fr] lg:items-center"><div><p className="eyebrow text-[#E2BA66]">The real problem</p><h2 className="section-title mt-5 text-white">Every app shows a slice. You carry the connection work.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#CBD4CF]">Your bank knows a balance. Your card knows a due date. Your UPI app knows a payment. Your household knows the shared costs. The mental stitching still lands with you.</p></div><div className="relative min-h-[330px] rounded-[1.75rem] border border-white/15 bg-[#143B35] p-5 sm:p-8"><div className="absolute inset-x-8 top-1/2 h-px -translate-y-1/2 bg-[#E2BA66]/30" />{fragments.map((fragment, index) => <div className={`absolute rounded-xl border border-white/15 bg-[#204B43] px-3.5 py-2.5 text-sm font-bold text-[#FDF9F0] shadow-lg ${["left-[7%] top-[9%]", "left-[30%] top-[25%]", "right-[8%] top-[11%]", "right-[22%] top-[38%]", "left-[10%] bottom-[15%]", "left-[39%] bottom-[7%]", "right-[6%] bottom-[13%]", "right-[34%] bottom-[27%]"][index]} motion-safe:animate-[drift_6s_ease-in-out_infinite]`} style={{ animationDelay: `${index * -0.7}s` }} key={fragment}>{fragment}</div>)}<p className="absolute bottom-5 left-6 right-6 text-center text-sm leading-6 text-[#AAB6AE]">Every piece can be useful. But a decision needs the relationship between them.</p></div></div></section>
    <section id="how-kubear-helps" className="paper-grid px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><div className="grid gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-end"><div><p className="eyebrow text-[#C96632]">The Kubear difference</p><h2 className="section-title mt-5">From scattered facts to a financial picture with context.</h2></div><p className="lede">The product story is simple: the pieces you choose to connect belong in one understandable layer, not another noisy feed.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{outcomes.map((outcome, index) => { const Icon = outcome.icon; return <article className={`rounded-[1.5rem] border border-[#102B28]/12 bg-[#FEFCF7] p-7 shadow-[0_12px_35px_rgba(16,43,40,0.06)] ${index === 1 ? "lg:translate-y-8" : ""}`} key={outcome.title}><span className="grid size-11 place-items-center rounded-xl bg-[#E7DED0] text-[#C96632]"><Icon className="size-5" /></span><p className="mt-9 font-serif text-5xl leading-none text-[#D6C7B5]">0{index + 1}</p><h3 className="mt-3 text-2xl font-bold tracking-[-0.045em] text-[#102B28]">{outcome.title}</h3><p className="mt-4 leading-7 text-[#53625B]">{outcome.text}</p></article>; })}</div></div></section>
    <section className="mx-5 overflow-hidden rounded-[2rem] bg-[#E7DED0] sm:mx-8 lg:mx-12"><div className="mx-auto grid max-w-[1440px] gap-8 lg:grid-cols-[1fr_0.95fr] lg:items-center"><LedgerScene className="min-h-[360px] rounded-none border-0 shadow-none" /><div className="px-7 py-14 sm:px-10 lg:px-14"><p className="eyebrow text-[#C96632]">The Connected Ledger</p><h2 className="section-title mt-5">A scattered financial life, resolving without the spreadsheet.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#53625B]">This is the Kubear “wow” moment: salary, UPI, bills, SIPs and shared costs stop behaving like tabs you have to remember. They become one composed picture that gives the next decision a little more context.</p><div className="margin-note mt-7">The picture is not another account. It is the context between the accounts.</div><a href="/how-it-works" className="mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-[#102B28] hover:text-[#C96632]">How the picture comes together <MoveRight className="size-4" /></a></div></div></section>
    <section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[0.88fr_1.12fr] lg:items-center"><div><p className="eyebrow text-[#C96632]">Personal & home</p><h2 className="section-title mt-5">Share the rent. Keep the rest yours.</h2><p className="mt-6 text-lg leading-8 text-[#53625B]">A shared household needs a financial view of its own. Your personal savings and spending deserve one too. Kubear’s current materials describe a way to keep those spaces distinct.</p><a href="/your-money-picture" className="button button-secondary mt-8">Explore your money picture <ArrowRight className="size-4" /></a></div><div className="relative overflow-hidden rounded-[1.75rem] border border-[#102B28]/10 bg-[#FEFCF7] p-6 shadow-[0_16px_45px_rgba(16,43,40,0.08)]"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-[#102B28]/10 p-5"><p className="eyebrow text-[#6E756C]">Personal · private</p><p className="mt-6 text-2xl font-bold tracking-[-0.045em] text-[#102B28]">Your own picture</p><div className="mt-5 space-y-3"><div className="h-2 w-4/5 rounded-full bg-[#143B35]" /><div className="h-2 w-3/5 rounded-full bg-[#E2BA66]" /><div className="h-2 w-2/5 rounded-full bg-[#C96632]" /></div></div><div className="rounded-2xl bg-[#143B35] p-5 text-[#FDF9F0]"><p className="eyebrow text-[#E2BA66]">Home · shared</p><p className="mt-6 text-2xl font-bold tracking-[-0.045em]">The things that need a common view</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-lg bg-white/10 px-2.5 py-1 text-xs font-bold">Rent</span><span className="rounded-lg bg-white/10 px-2.5 py-1 text-xs font-bold">Groceries</span><span className="rounded-lg bg-white/10 px-2.5 py-1 text-xs font-bold">Bills</span></div></div></div><p className="mt-5 text-sm leading-6 text-[#65726C]">Illustrative presentation based on published Kubear “Personal & Home” material. Verify the current product flow before using as a product claim.</p></div></div></section>
    <section className="bg-[#F4EFE4] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_1fr] lg:items-center"><LedgerEvidence variant="life" /><div><p className="eyebrow text-[#C96632]">Life, not just money</p><h2 className="section-title mt-5">The choices behind a number deserve a place in the picture.</h2><p className="mt-6 text-lg leading-8 text-[#53625B]">Money is rarely just money. It sits next to a move, a family, a career break, a home, a trip or the quieter desire to feel prepared. Kubear’s job begins with a clearer view of the information behind those decisions.</p></div></div></section>
    <section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><div className="max-w-3xl"><p className="eyebrow text-[#C96632]">The alternative</p><h2 className="section-title mt-5">Useful tools do different jobs.</h2><p className="lede mt-5">Kubear does not need to call a spreadsheet or specialist app bad to explain why another layer can help.</p></div><div className="mt-12 overflow-hidden rounded-[1.5rem] border border-[#102B28]/12 bg-[#FEFCF7]"><div className="grid grid-cols-[0.8fr_1fr_1fr_1fr] border-b border-[#102B28]/10 bg-[#E7DED0] text-sm font-extrabold text-[#102B28]"><div className="p-4">A decision needs</div><div className="p-4">Spreadsheet</div><div className="p-4">Specialist app</div><div className="p-4 text-[#C96632]">Kubear</div></div>{[["Calculation", "Strong", "Depends on the app", "Context around the calculation"], ["A view across pieces", "Manual upkeep", "Usually one slice", "Designed to compose what you connect"], ["Money movement", "No", "Often yes", "No—read-only by design"], ["The question behind it", "You build the formula", "Depends on the feature", "Plain-language context"]].map((row) => <div className="grid grid-cols-[0.8fr_1fr_1fr_1fr] border-b border-[#102B28]/10 last:border-b-0 text-sm" key={row[0]}>{row.map((cell, index) => <div className={`p-4 leading-6 ${index === 0 ? "font-bold text-[#102B28]" : index === 3 ? "bg-[#F6E6DD] font-semibold text-[#5E301B]" : "text-[#53625B]"}`} key={cell}>{cell}</div>)}</div>)}</div><p className="mt-5 text-sm leading-6 text-[#65726C]">This comparison describes product roles, not a universal ranking. Actual capability must be confirmed as Kubear evolves.</p></div></section>
    <section className="bg-[#102B28] px-5 py-20 text-[#FDF9F0] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.86fr_1.14fr] lg:items-center"><div><p className="eyebrow text-[#E2BA66]">Trust & control</p><h2 className="section-title mt-5 text-white">Built for financial data, not attention.</h2><p className="mt-6 text-lg leading-8 text-[#CBD4CF]">For money information, the details matter. A visitor should understand the limits of access before they consider connecting anything.</p><a href="/privacy-data" className="button button-light mt-8">Read privacy & data <ArrowRight className="size-4" /></a></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-[1.5rem] bg-[#143B35] p-6"><Eye className="size-6 text-[#E2BA66]" /><h3 className="mt-7 text-xl font-bold">Read-only access</h3><p className="mt-3 leading-7 text-[#CBD4CF]">Published Kubear material says it can show the picture but cannot move your money.</p></div><div className="rounded-[1.5rem] bg-[#143B35] p-6 sm:translate-y-7"><LockKeyhole className="size-6 text-[#E2BA66]" /><h3 className="mt-7 text-xl font-bold">Private by default</h3><p className="mt-3 leading-7 text-[#CBD4CF]">Published policy says people choose what to connect and data is not sold to advertisers.</p></div><div className="rounded-[1.5rem] bg-[#143B35] p-6"><UsersRound className="size-6 text-[#E2BA66]" /><h3 className="mt-7 text-xl font-bold">Control stays close</h3><p className="mt-3 leading-7 text-[#CBD4CF]">Published materials describe disconnect and deletion routes. Details should always remain findable.</p></div><div className="rounded-[1.5rem] bg-[#143B35] p-6 sm:translate-y-7"><Sparkles className="size-6 text-[#E2BA66]" /><h3 className="mt-7 text-xl font-bold">No noisy upsells</h3><p className="mt-3 leading-7 text-[#CBD4CF]">The product story is a calm financial layer—not another feed competing for attention.</p></div></div></div></section>
    <section className="paper-grid px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.78fr_1.22fr]"><div><p className="eyebrow text-[#C96632]">Questions worth asking</p><h2 className="section-title mt-5">A good answer should be easy to find.</h2><p className="mt-5 leading-7 text-[#53625B]">These are the questions an unfamiliar visitor, an Excel user and a privacy-conscious visitor will ask. The language is kept factual and the boundaries are explicit.</p></div><Accordion type="single" collapsible className="rounded-[1.5rem] border border-[#102B28]/12 bg-[#FEFCF7] px-6 sm:px-8">{faqs.map(([question, answer], index) => <AccordionItem value={`faq-${index}`} key={question}><AccordionTrigger className="py-6 text-base font-extrabold text-[#102B28] no-underline hover:no-underline sm:text-lg">{question}</AccordionTrigger><AccordionContent className="max-w-2xl pb-6 text-base leading-7 text-[#53625B]">{answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="px-5 pb-20 sm:px-8 lg:px-12 lg:pb-28"><div className="mx-auto max-w-[1280px] overflow-hidden rounded-[2rem] bg-[#C96632] px-7 py-14 sm:px-10 lg:px-16 lg:py-16"><div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="eyebrow text-[#FCEBDD]">Early access · India</p><h2 className="mt-5 font-serif text-5xl leading-[0.94] tracking-[-0.06em] text-[#fffaf4] sm:text-6xl">Stop stitching it together. See the full picture.</h2><p className="mt-6 max-w-xl text-lg leading-8 text-[#FCEBDD]">Join the early version of Kubear and help shape a calmer way to understand everyday money.</p></div><a className="button button-light shrink-0" href="https://kubear.kuberos.in" target="_blank" rel="noreferrer">Join early access <ArrowUpRight className="size-4" /></a></div></div></section>
  </SiteLayout>;
}
