/* Living Ledger modernisation: this route explains the product like a helpful friend, in three easy steps with a visible money view. */
import { ArrowUpRight, Eye, Layers3, SlidersHorizontal } from "lucide-react";
import { PageMeta } from "@/components/PageMeta";
import { LedgerEvidence } from "@/components/LedgerEvidence";
import { LedgerScene } from "@/components/LedgerScene";
import { SiteLayout } from "@/components/SiteChrome";

const steps = [
  { number: "01", icon: SlidersHorizontal, title: "Pick what you want to see", text: "Choose the accounts and money details you want Kubear to look at. You stay in control." },
  { number: "02", icon: Layers3, title: "Bring the pieces together", text: "Your money coming in, money going out and bills due can sit in one simple view." },
  { number: "03", icon: Eye, title: "See what needs your attention", text: "Check what changed, what is due and what you may want to think about before the next money move." },
];

export default function HowItWorks() {
  return <SiteLayout><PageMeta title="How Kubear works | See your money clearly" description="In three simple steps, Kubear helps you see the financial information you choose to connect in one read-only view." path="/how-it-works" /><section className="paper-grid overflow-hidden px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:px-12 lg:pb-28"><div className="mx-auto max-w-[1280px]"><p className="eyebrow text-[#C96632]">How it works</p><div className="mt-6 grid gap-10 lg:grid-cols-[0.92fr_1.08fr] lg:items-end"><div data-reveal><h1 className="display text-[#102B28]">Three simple steps. More clarity.</h1><p className="lede mt-7">You do not need another finance app shouting at you. You need one simple view of the money you choose to connect.</p><a className="button button-primary mt-8" href="https://kubear.kuberos.in" target="_blank" rel="noreferrer">Join early access <ArrowUpRight className="size-4" /></a></div><LedgerEvidence variant="flow" /></div></div></section><section className="bg-[#102B28] px-5 py-20 text-[#FDF9F0] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><p className="eyebrow text-[#E2BA66]">The simple flow</p><div className="mt-10 grid gap-5 lg:grid-cols-3">{steps.map((step) => { const Icon = step.icon; return <article className="ledger-step" data-reveal key={step.number}><span className="font-serif text-5xl text-[#E2BA66]">{step.number}</span><Icon className="mt-10 size-6 text-[#E2BA66]" /><h2 className="mt-4 text-2xl font-bold tracking-[-0.04em]">{step.title}</h2><p className="mt-4 max-w-sm leading-7 text-[#CBD4CF]">{step.text}</p></article>; })}</div></div></section><section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div data-reveal><p className="eyebrow text-[#C96632]">One important thing</p><h2 className="section-title mt-5">Just see. No money moves from here.</h2></div><div className="space-y-6 text-lg leading-8 text-[#42514B]" data-reveal><p>Kubear’s public information describes a read-only model. It can show the money information you choose to connect. It does not move your money.</p><p className="margin-note">Your bank, UPI app and investing app keep doing their job. Kubear helps you see the story between them.</p><p className="text-sm leading-6 text-[#65726C]">Product details should be checked against Kubear’s latest approved public information before launch.</p></div></div></section></SiteLayout>;
}
