/* Week Comes Together: three clear steps connect a calm marketing story to the real Kubear app without implying money movement. */
import { ArrowUpRight, Eye, Layers3, SlidersHorizontal } from "lucide-react";
import { PageMeta } from "@/components/PageMeta";
import { MoneyFlowInstrument } from "@/components/TactileMoneyInstruments";
import { SiteLayout } from "@/components/SiteChrome";

const APP_URL = "https://kubear.kuberos.in";
const steps = [
  { number: "01", icon: SlidersHorizontal, title: "Pick what you want to see", text: "Choose the accounts and money details you want Kubear to look at. You stay in control." },
  { number: "02", icon: Layers3, title: "Bring the pieces together", text: "Your money coming in, money going out and bills due can sit in one simple view." },
  { number: "03", icon: Eye, title: "See what needs your attention", text: "Check what changed, what is due and what you may want to think about before the next money move." },
];

export default function HowItWorks() {
  return <SiteLayout><PageMeta title="How Kubear works | See your money clearly" description="In three simple steps, Kubear helps you see the financial information you choose to connect in one read-only view." path="/how-it-works" /><section className="paper-grid overflow-hidden px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:px-12 lg:pb-28"><div className="mx-auto max-w-[1280px]"><p className="eyebrow text-[#FF6A35]">How it works</p><div className="mt-6 grid gap-10 lg:grid-cols-[0.92fr_1.08fr] lg:items-end"><div data-reveal><h1 className="display text-[#14312E]">Three simple steps. More clarity.</h1><p className="lede mt-7">You do not need another finance app shouting at you. You need one simple view of the money you choose to connect.</p><a className="button button-orange mt-8" href={APP_URL}>Open Kubear <ArrowUpRight className="size-4" /></a></div><MoneyFlowInstrument /></div></div></section><section className="bg-[#092B27] px-5 py-20 text-[#FFF4E6] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><p className="eyebrow text-[#FFE7A4]">The simple flow</p><div className="mt-10 grid gap-5 lg:grid-cols-3">{steps.map((step) => { const Icon = step.icon; return <article className="ledger-step" data-reveal key={step.number}><span className="font-serif text-5xl text-[#FFE7A4]">{step.number}</span><Icon className="mt-10 size-6 text-[#FFE7A4]" /><h2 className="mt-4 text-2xl font-bold tracking-[-0.04em]">{step.title}</h2><p className="mt-4 max-w-sm leading-7 text-[#D8E2DC]">{step.text}</p></article>; })}</div></div></section><section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div data-reveal><p className="eyebrow text-[#FF6A35]">One important thing</p><h2 className="section-title mt-5">Just see. No money moves from here.</h2></div><div className="space-y-6 text-lg leading-8 text-[#42514B]" data-reveal><p>Kubear’s public information describes a read-only model. It can show the money information you choose to connect. It does not move your money.</p><p className="margin-note">Your bank, UPI app and investing app keep doing their job. Kubear helps you see the story between them.</p><p className="text-sm leading-6 text-[#65726C]">Product details should be checked against Kubear’s latest approved public information before launch.</p></div></div></section></SiteLayout>;
}
