/* Living Ledger modernisation: the learning surface speaks in clear, familiar Indian money questions instead of dense finance language. */
import { ArrowUpRight } from "lucide-react";
import { LedgerEvidence } from "@/components/LedgerEvidence";
import { PageMeta } from "@/components/PageMeta";
import { SiteLayout } from "@/components/SiteChrome";

const articles = [
  { category: "Trust", title: "Is Account Aggregator safe? Here is the simple answer.", desc: "A quick way to understand how consent based financial data sharing works.", href: "https://www.kuberos.in/blog/account-aggregator-safety" },
  { category: "Product", title: "22 apps. One phone. Too much to track.", desc: "Why your money can still feel scattered even when every app is working fine.", href: "https://www.kuberos.in/blog/22-apps-1-screen" },
  { category: "Money", title: "PPF, EPF and NPS. What is the difference?", desc: "A simple starting point for three familiar long-term saving options.", href: "https://www.kuberos.in/blog/ppf-vs-epf-vs-nps" },
  { category: "Guides", title: "Old or new tax regime. Which one may work for you?", desc: "A plain guide to a tax question that comes up every year.", href: "https://www.kuberos.in/blog/old-vs-new-regime-fy-2025-26" },
];

export default function Journal() {
  return <SiteLayout><PageMeta title="Kubear Learn | Money talk, no jargon" description="Short, simple notes from Kubear about everyday Indian money questions." path="/journal" /><section className="paper-grid px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><p className="eyebrow text-[#C96632]">Kubear Learn</p><div className="mt-6 grid gap-10 lg:grid-cols-[0.9fr_1.1fr]"><h1 className="display text-[#102B28]" data-reveal>Money talk. No jargon.</h1><p className="lede self-end" data-reveal>Short guides for the money questions that come up in real life. Simple words. No lecture.</p></div></div></section><section className="px-5 pb-20 sm:px-8 lg:px-12 lg:pb-28"><div className="mx-auto max-w-[1280px]"><article className="overflow-hidden rounded-[2rem] bg-[#102B28] text-[#FDF9F0] sm:grid sm:grid-cols-[1.2fr_0.8fr]" data-reveal><div className="p-7 sm:p-10"><p className="eyebrow text-[#E2BA66]">Featured · Money</p><h2 className="mt-7 max-w-2xl font-serif text-4xl leading-[0.98] tracking-[-0.055em] sm:text-5xl">Kids’ investing. Where should you begin?</h2><p className="mt-6 max-w-xl leading-7 text-[#CBD4CF]">Bachche ke naam pe SIP? PPF? Sukanya? Start with the basics.</p><a href="https://www.kuberos.in/blog/investing-for-kids-india" target="_blank" rel="noreferrer" className="button button-light mt-8">Read the guide <ArrowUpRight className="size-4" /></a></div><div className="border-t border-white/20 bg-[#143B35] p-5 sm:border-l sm:border-t-0 sm:p-8"><LedgerEvidence variant="journal" /><p className="mt-5 text-sm leading-6 text-[#CBD4CF]">Good money advice starts with a clear question, not a sales pitch.</p></div></article><div className="journal-index mt-10">{articles.map((article, index) => <a data-reveal key={article.title} href={article.href} target="_blank" rel="noreferrer" className="journal-entry group"><span>0{index + 1}</span><div><p className="eyebrow text-[#C96632]">{article.category}</p><h2>{article.title}</h2><p>{article.desc}</p></div><ArrowUpRight className="journal-entry-arrow size-5" /></a>)}</div></div></section></SiteLayout>;
}
