/* Week Comes Together: familiar money questions lead to a direct Kubear app handoff, with no generic early-access dead end. */
import { ArrowUpRight, CalendarClock, CircleHelp, Landmark, UsersRound, WalletCards } from "lucide-react";
import { PageMeta } from "@/components/PageMeta";
import { MoneyViewSnapshot } from "@/components/TactileMoneyInstruments";
import { SiteLayout } from "@/components/SiteChrome";

const APP_URL = "https://kubear.kuberos.in";
const modules = [
  { icon: Landmark, tag: "Your money", title: "See what you really have", body: "Your balance makes more sense when you see it with the money you chose to connect." },
  { icon: CalendarClock, tag: "Coming up", title: "See what is due next", body: "Keep bills, subscriptions and planned payments close to the money they affect." },
  { icon: WalletCards, tag: "Your spend", title: "Know what you can spend", body: "See what is already booked before you make an everyday spending choice." },
  { icon: CircleHelp, tag: "Your question", title: "Ask in simple words", body: "Ask the question in your head, without putting together five different app screens first." },
  { icon: UsersRound, tag: "Your home", title: "Keep home and personal money clear", body: "Rent and bills can have a shared view. Your personal money can stay personal." },
];

export default function MoneyPicture() {
  return <SiteLayout><PageMeta title="Your money | Kubear" description="See the money questions Kubear is built to make simpler, from bills due to what you can spend." path="/your-money-picture" /><section className="money-view-hero px-5 py-20 text-[#FFF4E6] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.92fr_1.08fr] lg:items-center"><div data-reveal><p className="eyebrow text-[#FFE7A4]">Your money view</p><h1 className="display mt-5">Your balance is one number. Your money has a story.</h1><p className="lede mt-7 text-[#D8E2DC]">A balance does not tell you about rent, a card bill, your SIP or the plan you have this weekend. The full picture does.</p></div><MoneyViewSnapshot /></div></section><section className="paper-grid px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]"><div className="staggered-list">{modules.map((module, index) => { const Icon = module.icon; return <article data-reveal className={`outcome-row ${index === 1 ? "lg:ml-[12%]" : ""} ${index === 3 ? "lg:ml-[6%]" : ""}`} key={module.title}><div className="flex items-start gap-5"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#FCE4D9] text-[#FF6A35]"><Icon className="size-5" /></span><div><p className="eyebrow text-[#FF6A35]">{module.tag}</p><h2 className="mt-2 text-2xl font-bold tracking-[-0.045em] text-[#14312E] sm:text-3xl">{module.title}</h2><p className="mt-3 max-w-xl leading-7 text-[#53625B]">{module.body}</p></div></div><span className="hidden font-serif text-5xl text-[#D6C7B5] md:block">0{index + 1}</span></article>; })}</div></div></section><section className="money-view-cta mx-5 mb-20 overflow-hidden rounded-[2rem] px-6 py-14 sm:mx-8 sm:px-10 lg:mx-12 lg:mb-28 lg:px-16"><div className="mx-auto flex max-w-[1150px] flex-col gap-8 md:flex-row md:items-end md:justify-between" data-reveal><div className="max-w-2xl"><p className="eyebrow">Good apps. One clearer view.</p><h2 className="mt-4 font-serif text-4xl leading-[0.95] tracking-[-0.055em] sm:text-5xl">Not another app to manage. One easier way to see.</h2></div><a href={APP_URL} className="button button-orange shrink-0">Open Kubear <ArrowUpRight className="size-4" /></a></div></section></SiteLayout>;
}
