/* Living Ledger modernisation: privacy is explained like a human promise, with short proof points and no security theatre. */
import { ArrowRight, Eye, KeyRound, Trash2 } from "lucide-react";
import { LedgerEvidence } from "@/components/LedgerEvidence";
import { PageMeta } from "@/components/PageMeta";
import { SiteLayout } from "@/components/SiteChrome";

const points = [
  { icon: Eye, title: "Just look. Do not move money.", text: "Kubear’s public information says it can show what you connect, but it cannot move your money." },
  { icon: KeyRound, title: "No bank password or UPI PIN", text: "The public privacy page says Kubear does not collect bank passwords, UPI PINs, OTPs or card CVVs." },
  { icon: Trash2, title: "Leave when you want", text: "The published delete-account flow says you can remove your account, connected information and chat history." },
];

export default function PrivacyData() {
  return <SiteLayout><PageMeta title="Privacy | Kubear" description="A simple guide to Kubear’s published read-only access and data-control commitments." path="/privacy-data" /><section className="bg-[#E7DED0] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[1fr_0.9fr] lg:items-end"><div data-reveal><p className="eyebrow text-[#C96632]">Privacy</p><h1 className="display mt-5 text-[#102B28]">Your money. Your data. Your control.</h1><p className="lede mt-7">You should know what an app can see, what it cannot do and how to stop using it. No confusing fine print.</p><div className="margin-note mt-7">See the full picture without giving up control.</div></div><LedgerEvidence variant="privacy" /></div></section><section className="px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1280px]">{points.map((point, index) => { const Icon = point.icon; return <article data-reveal className={`ledger-entry ${index === 1 ? "lg:ml-[9%]" : ""}`} key={point.title}><span className="ledger-entry-number">0{index + 1}</span><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#F6E6DD] text-[#C96632]"><Icon className="size-5" /></span><div><p className="eyebrow text-[#C96632]">Clear control</p><h2 className="mt-2 text-2xl font-bold tracking-[-0.045em] text-[#102B28]">{point.title}</h2><p className="mt-3 max-w-xl leading-7 text-[#53625B]">{point.text}</p></div><span className="ledger-entry-rule" /></article>; })}</div></section><section className="bg-[#102B28] px-5 py-20 text-[#FDF9F0] sm:px-8 lg:px-12 lg:py-28"><div className="mx-auto grid max-w-[1280px] gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div data-reveal><p className="eyebrow text-[#E2BA66]">In simple words</p><h2 className="section-title mt-5 text-white">What Kubear says today.</h2></div><div className="space-y-5 text-base leading-7 text-[#D6DFD9]" data-reveal><p>The current privacy policy says that data is not sold, rented or shared with advertisers. It also says you choose the accounts you connect.</p><p>The current terms say Kubear is a personal finance assistant. It is not a bank, broker, investment adviser or payment service.</p><p className="margin-note border-[#E2BA66] text-white">Before this goes live, Kubear should check every privacy, consent and feature statement against its latest approved policy.</p><a href="https://www.kuberos.in/legal/privacy-policy" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 font-bold text-[#E2BA66] hover:text-white">Read the current privacy policy <ArrowRight className="size-4" /></a></div></div></section></SiteLayout>;
}
