import { LifeNodeData } from "./types";

export const SALARY_AMOUNT = 100000;
export const SALARY_LABEL = "Salary Received";
export const SALARY_FORMATTED = "₹1,00,000";

// SVG coordinate space: 760 x 580
// Coordinates carefully calculated to match the background photograph and provide open breathing room:
// - Person's head is around x: 420-470, y: 350-480 (in LifeMap space)
// - Laptop is around center-bottom x: 330-430, y: 440-540
// - Dog is at bottom right x: 580-680, y: 440-540
// - Open negative space on left (x: 10%-25%) and right (x: 75%-92%)
// - Safe bounds: left > 6%, right < 94%, top > 6%, bottom < 88%

export const LIFE_NODES: LifeNodeData[] = [
  {
    id: "home",
    category: "HOME",
    label: "Home & Rent",
    amount: 28000,
    formattedAmount: "₹28,000",
    iconType: "home",
    desktopPos: { xPercent: 24, yPercent: 16 },
    svgEndCoord: { x: 182, y: 93 },
    microContext: "Due 5th · Shelter & security",
    accentColor: "#D97706",
    glowColor: "rgba(217, 119, 6, 0.14)",
    floatingDelay: 0,
    scale: 1.05,
    depth: "front",
    pathOpacity: 0.42,
  },
  {
    id: "investments",
    category: "INVESTMENTS",
    label: "Investments (SIP)",
    amount: 15000,
    formattedAmount: "₹15,000",
    iconType: "investments",
    desktopPos: { xPercent: 71, yPercent: 13 },
    svgEndCoord: { x: 540, y: 75 },
    microContext: "Index funds & compounding wealth",
    accentColor: "#059669",
    glowColor: "rgba(5, 150, 105, 0.14)",
    floatingDelay: 0.7,
    scale: 1.02,
    depth: "back",
    pathOpacity: 0.46,
  },
  {
    id: "travel",
    category: "TRAVEL",
    label: "Travel & Experiences",
    amount: 8000,
    formattedAmount: "₹8,000",
    iconType: "travel",
    desktopPos: { xPercent: 88, yPercent: 22 },
    svgEndCoord: { x: 668, y: 128 },
    microContext: "Weekend escape · Clear to spend",
    accentColor: "#EA580C",
    glowColor: "rgba(234, 88, 12, 0.16)",
    floatingDelay: 1.5,
    scale: 1.1,
    labelWidth: "min-w-[124px]",
    depth: "front",
    pathOpacity: 0.48,
  },
  {
    id: "emi",
    category: "EMI",
    label: "EMI & Loans",
    amount: 12500,
    formattedAmount: "₹12,500",
    iconType: "emi",
    desktopPos: { xPercent: 18, yPercent: 44 },
    svgEndCoord: { x: 137, y: 255 },
    microContext: "Auto-debited · Paid on time",
    accentColor: "#0F766E",
    glowColor: "rgba(15, 118, 110, 0.12)",
    floatingDelay: 1.1,
    scale: 0.98,
    depth: "back",
    pathOpacity: 0.38,
  },
  {
    id: "family",
    category: "FAMILY",
    label: "Family Support",
    amount: 10000,
    formattedAmount: "₹10,000",
    iconType: "family",
    desktopPos: { xPercent: 88, yPercent: 44 },
    svgEndCoord: { x: 668, y: 255 },
    microContext: "Parents & shared moments",
    accentColor: "#C2410C",
    glowColor: "rgba(194, 65, 12, 0.14)",
    floatingDelay: 1.8,
    scale: 0.98,
    depth: "front",
    pathOpacity: 0.4,
  },
  {
    id: "everyday",
    category: "EVERYDAY LIFE",
    label: "Everyday Spending",
    amount: 15000,
    formattedAmount: "₹15,000",
    iconType: "everyday",
    desktopPos: { xPercent: 18, yPercent: 72 },
    svgEndCoord: { x: 137, y: 418 },
    microContext: "Dining, rhythm & groceries",
    accentColor: "#B45309",
    glowColor: "rgba(180, 83, 9, 0.12)",
    floatingDelay: 2.2,
    scale: 1.0,
    depth: "front",
    pathOpacity: 0.34,
  },
  {
    id: "emergency",
    category: "EMERGENCY",
    label: "Insurance & Emergency",
    amount: 5000,
    formattedAmount: "₹5,000",
    iconType: "emergency",
    desktopPos: { xPercent: 86, yPercent: 70 },
    svgEndCoord: { x: 654, y: 406 },
    microContext: "Liquid buffer for peace of mind",
    accentColor: "#047857",
    glowColor: "rgba(4, 120, 87, 0.12)",
    floatingDelay: 0.9,
    scale: 0.94,
    labelWidth: "min-w-[124px]",
    depth: "back",
    pathOpacity: 0.36,
  },
];


