/* Mobile-first planning workspace: typed local formulas, transparent assumptions and clear updated states make each tool feel reliably live. */
import { motion } from "framer-motion";
import { ArrowRight, ChevronDown, Info, RotateCcw, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { emiEstimate, goalEstimate, readNumber, sipEstimate } from "@/lib/calculatorMath";
import { getTool, tools } from "@/lib/contentRegistry";
import { CalculatorLogicInstrument, ToolBenchInstrument } from "@/components/TactileMoneyInstruments";

type CalculatorKind = "sip" | "emi" | "goa";
type FormState = { monthly: string; rate: string; years: string; loan: string; target: string; saved: string; targetMonth: string };
const initialFor = (slug: string): FormState => ({ monthly: "5000", rate: slug === "sip-calculator" ? "12" : "8.5", years: slug === "sip-calculator" ? "10" : "5", loan: "2500000", target: "60000", saved: "15000", targetMonth: "2027-01" });
const formatInr = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number.isFinite(value) ? Math.max(0, value) : 0);
const currentMonth = () => new Date().toISOString().slice(0, 7);
const firstInvalidMessage = (...values: { valid: boolean; message?: string }[]) => values.find((value) => !value.valid)?.message ?? "Check the values and try again.";

function NumberField({ label, value, onChange, suffix = "₹", min = 0, max, step = 1, hint }: { label: string; value: string; onChange: (value: string) => void; suffix?: string; min?: number; max?: number; step?: number; hint?: string }) {
  const valueState = value.trim() === "" || !Number.isFinite(Number(value)) || Number(value) < min || (max !== undefined && Number(value) > max) ? "is-invalid" : "";
  return <label className={`calc-field ${valueState}`}><span>{label}</span><div><input type="number" inputMode="decimal" min={min} max={max} step={step} value={value} onChange={(event) => onChange(event.target.value)} aria-invalid={Boolean(valueState)} aria-describedby={hint ? `${label.replace(/\W/g, "")}-hint` : undefined} /><b aria-hidden="true">{suffix}</b></div>{hint ? <small id={`${label.replace(/\W/g, "")}-hint`}>{hint}</small> : null}</label>;
}

export function CalculatorExperience({ slug }: { slug: string }) {
  const tool = getTool(slug); const kind = (tool?.visual ?? "sip") as CalculatorKind;
  const [form, setForm] = useState<FormState>(() => initialFor(slug));
  useEffect(() => setForm(initialFor(slug)), [slug]);
  const set = (field: keyof FormState) => (value: string) => setForm((previous) => ({ ...previous, [field]: value }));
  const result = useMemo(() => {
    if (kind === "sip") { const monthly = readNumber(form.monthly, "Monthly SIP", { min: 1 }); const rate = readNumber(form.rate, "Expected annual return", { min: 0, max: 100 }); const years = readNumber(form.years, "Years", { min: 1, max: 70 }); if (!monthly.valid || !rate.valid || !years.valid) return { valid: false as const, message: firstInvalidMessage(monthly, rate, years) }; const estimate = sipEstimate(monthly.value, rate.value, years.value); return { valid: true as const, main: estimate.value, label: "Estimated value", detailA: `You put in ${formatInr(estimate.contributed)}`, detailB: `Estimated growth ${formatInr(estimate.growth)}`, explanation: `This estimate assumes ${rate.value}% per year for ${estimate.periods} monthly contributions.` }; }
    if (kind === "emi") { const loan = readNumber(form.loan, "Loan amount", { min: 1 }); const rate = readNumber(form.rate, "Annual interest rate", { min: 0, max: 100 }); const years = readNumber(form.years, "Tenure", { min: 1, max: 50 }); if (!loan.valid || !rate.valid || !years.valid) return { valid: false as const, message: firstInvalidMessage(loan, rate, years) }; const estimate = emiEstimate(loan.value, rate.value, years.value); return { valid: true as const, main: estimate.emi, label: "Estimated monthly EMI", detailA: `Total payment ${formatInr(estimate.total)}`, detailB: `Estimated interest ${formatInr(estimate.interest)}`, explanation: `This estimate uses ${rate.value}% annual interest over ${estimate.periods} months.` }; }
    const target = readNumber(form.target, "Goa plan amount", { min: 1 }); const saved = readNumber(form.saved, "Already saved", { min: 0 }); if (!target.valid || !saved.valid) return { valid: false as const, message: firstInvalidMessage(target, saved) }; const estimate = goalEstimate(target.value, saved.value, form.targetMonth); if (estimate.complete) return { valid: true as const, main: 0, label: "Your Goa plan is fully saved", detailA: "Nothing left to set aside", detailB: "Goal already met", explanation: "Nice work. You can change the amount or month to plan the next trip." }; if (estimate.overdue) return { valid: false as const, message: "Choose a future target month to see a useful monthly estimate." }; return { valid: true as const, main: estimate.monthly, label: "Estimated amount to set aside each month", detailA: `${formatInr(estimate.remaining)} still to save`, detailB: `${estimate.months} months to go`, explanation: "This is a simple no-return estimate. It spreads the remaining goal across the months left." };
  }, [form, kind]);
  if (!tool) return null;
  const reset = () => setForm(initialFor(slug));
  const fields = kind === "sip" ? <><NumberField label="Monthly SIP" value={form.monthly} onChange={set("monthly")} /><NumberField label="Expected annual return" value={form.rate} onChange={set("rate")} suffix="%" step={0.1} max={100} hint="This is only an assumption, not a promise." /><NumberField label="Years" value={form.years} onChange={set("years")} suffix="years" min={1} max={70} /></> : kind === "emi" ? <><NumberField label="Loan amount" value={form.loan} onChange={set("loan")} /><NumberField label="Annual interest rate" value={form.rate} onChange={set("rate")} suffix="%" step={0.1} max={100} /><NumberField label="Tenure" value={form.years} onChange={set("years")} suffix="years" min={1} max={50} /></> : <><NumberField label="Goa plan amount" value={form.target} onChange={set("target")} /><NumberField label="Already saved" value={form.saved} onChange={set("saved")} /><label className="calc-field"><span>Target month</span><div><input type="month" min={currentMonth()} value={form.targetMonth} onChange={(event) => set("targetMonth")(event.target.value)} aria-label="Target month" /></div></label></>;
  const chips = kind === "sip" ? [1, 5, 10] : kind === "emi" ? [3, 5, 7] : [];
  return <div className="calculator-shell"><section className="tool-hero"><div><p className="week-kicker"><span /> {tool.eyebrow}</p><h1 className="week-section-title">{tool.title}. <em>Start simple.</em></h1><p className="week-lede">{tool.description}</p><p className="tool-hero-note"><Info className="size-4" /> Planning helper only. It is not personal financial advice.</p></div><CalculatorLogicInstrument kind={kind} /></section><section className="calc-workspace"><div className="calc-sheet" data-reveal><div className="calc-sheet-top"><span>01</span><p>Put in your numbers</p><button type="button" className="calc-reset" onClick={reset}><RotateCcw className="size-3.5" />Reset example</button></div><div className="calc-fields">{fields}</div>{chips.length ? <div className="quick-chips" aria-label="Set a planning period">{chips.map((year) => <button type="button" key={year} onClick={() => set("years")(String(year))} className={form.years === String(year) ? "is-selected" : ""}>{year} year{year > 1 ? "s" : ""}</button>)}</div> : null}</div><aside className="calc-answer" data-reveal aria-live="polite"><div className="calc-answer-top"><span>02</span><p>Your simple answer</p></div>{result.valid ? <><p className="calc-answer-label">{result.label}</p><motion.strong key={Math.round(result.main)} initial={{ opacity: 0.35, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.18 }}>{formatInr(result.main)}</motion.strong><div className="calc-answer-lines"><span>{result.detailA}</span><span>{result.detailB}</span></div><p className="calc-answer-note">{result.explanation}</p></> : <div className="calc-answer-empty"><Sparkles className="size-5" /><strong>Let’s make it useful.</strong><p>{result.message}</p></div>}</aside></section><section className="calc-details"><details><summary>How this calculation works <ChevronDown className="size-4" /></summary><p>{kind === "sip" ? "The estimate uses a standard monthly contribution calculation. Expected return is an input, not a guarantee." : kind === "emi" ? "The estimate uses the loan amount, monthly interest rate and the number of monthly payments." : "The estimate simply divides what is left to save by the number of months until the target date."}</p></details><Link href={`/learn/${tool.learnSlug}`} className="calc-read-next">Read the related guide <ArrowRight className="size-4" /></Link></section></div>;
}

export function ToolsHub() { return <div className="tools-hub"><section className="tools-hub-hero"><div><p className="week-kicker"><span /> Kubear Learn</p><h1 className="week-section-title">A number can be <em>a good first step.</em></h1><p className="week-lede">Salary day, a home plan or Goa. Pick the money moment first, then try the numbers you want to understand.</p></div><ToolBenchInstrument /></section><section className="tools-route-list">{tools.map((tool, index) => <Link href={`/learn/tools/${tool.slug}`} className="tool-route" key={tool.slug}><span>0{index + 1}</span><div><p className="eyebrow">{tool.eyebrow}</p><h2>{tool.title}</h2><p>{tool.description}</p></div><ArrowRight className="size-5" /></Link>)}</section><p className="tools-disclaimer">The tools are for illustration and planning. Their outputs are not recommendations, financial advice or a prediction of results.</p></div>; }
