/* Living Ledger refinement: each route gets a distinct composition of familiar money signals becoming one simple, governed view. */
import { ArrowDownRight, CalendarDays, Check, Eye, HeartHandshake, Landmark, LockKeyhole, ReceiptIndianRupee, ScanLine, WalletCards } from "lucide-react";

type Variant = "life" | "privacy" | "journal" | "flow" | "today" | "picture";

const lifeMarkers = ["Salary day", "Rent", "SIP", "School fee", "Weekend", "Family"];

export function LedgerEvidence({ variant }: { variant: Variant }) {
  if (variant === "flow") return <div className="evidence-scene evidence-flow" aria-label="Three familiar money steps coming together in a clear view"><div className="flow-line" /><div className="flow-card flow-card-a"><span>01</span><Landmark className="size-5" /><b>Pick what matters</b><small>Bank, UPI, card, SIP</small></div><div className="flow-card flow-card-b"><span>02</span><ScanLine className="size-5" /><b>See it together</b><small>Money in, money out, due</small></div><div className="flow-card flow-card-c"><span>03</span><Check className="size-5" /><b>Make a clearer call</b><small>One simple view</small></div><p className="flow-caption">Choose your money details. Then see how they fit.</p></div>;

  if (variant === "today") return <div className="evidence-scene evidence-today" aria-label="Illustrative today money view with Indian payment and bill reminders"><div className="today-tab">Aaj · this week</div><div className="today-sheet"><div className="today-header"><span><i />This week</span><b>₹18,400</b></div><div className="today-row"><Landmark className="size-4 text-[#4D7869]" /><span>Salary received</span><b className="text-[#4D7869]">Done</b></div><div className="today-row"><ReceiptIndianRupee className="size-4 text-[#C96632]" /><span>Card bill</span><b>Friday</b></div><div className="today-row"><ScanLine className="size-4 text-[#A46C1E]" /><span>UPI spends</span><b>This week</b></div><div className="today-row"><WalletCards className="size-4 text-[#4D7869]" /><span>Home rent</span><b>Pending</b></div></div><div className="today-slip today-slip-a">Card bill due Friday</div><div className="today-slip today-slip-b">SIP this week</div><p>Example only. Not live money data.</p></div>;

  if (variant === "picture") return <div className="evidence-scene evidence-picture" aria-label="Illustrative money fragments resolving into one clear picture"><div className="picture-thread picture-thread-a" /><div className="picture-thread picture-thread-b" /><div className="picture-fragment fragment-salary"><Landmark className="size-4" />Salary</div><div className="picture-fragment fragment-upi"><ScanLine className="size-4" />UPI</div><div className="picture-fragment fragment-sip"><ArrowDownRight className="size-4" />SIP</div><div className="picture-fragment fragment-rent"><WalletCards className="size-4" />Rent</div><div className="picture-ledger"><p className="eyebrow text-[#C96632]">Your money view</p><h3>One place to see what matters.</h3><div><span><i className="bg-[#4D7869]" />Money in</span><span><i className="bg-[#C96632]" />Bills due</span><span><i className="bg-[#E2BA66]" />Plans ahead</span></div></div></div>;

  if (variant === "life") return <div className="evidence-scene evidence-life" aria-label="Illustrative life moments linked through a copper money timeline"><div className="life-thread" />{lifeMarkers.map((marker, index) => <div className={`life-marker life-marker-${index}`} key={marker}><span>{String(index + 1).padStart(2, "0")}</span><b>{marker}</b></div>)}<div className="absolute bottom-5 left-6 right-6 border-l-2 border-[#C96632] pl-4 text-sm leading-6 text-[#53625B]">A money choice often shows up just before a real-life moment.</div></div>;

  if (variant === "privacy") return <div className="evidence-scene evidence-privacy" aria-label="Illustrative read-only financial information and user-control boundaries"><div className="privacy-folio"><div className="flex items-center justify-between"><span className="eyebrow text-[#C96632]">Your boundary</span><LockKeyhole className="size-4 text-[#143B35]" /></div><h3>What is in your view.</h3><div className="mt-5 space-y-3"><span className="evidence-row"><Landmark className="size-3.5" /> Account information <i>chosen</i></span><span className="evidence-row"><WalletCards className="size-3.5" /> Bills and plans <i>context</i></span><span className="evidence-row"><Eye className="size-3.5" /> Read-only view <i>no movement</i></span></div></div><div className="privacy-stub privacy-stub-a"><Eye className="size-3.5" /> See</div><div className="privacy-stub privacy-stub-b"><LockKeyhole className="size-3.5" /> Control</div><div className="privacy-stub privacy-stub-c">Disconnect anytime</div><p className="absolute bottom-5 left-6 right-6 text-center text-[0.68rem] font-bold uppercase tracking-[0.12em] text-[#65726C]">Example only. Not a live product screen.</p></div>;

  return <div className="evidence-scene evidence-journal" aria-label="Illustrative journal notes connecting everyday Indian money questions"><div className="journal-rule" /><div className="journal-note journal-note-a"><span className="eyebrow text-[#C96632]">UPI</span><b>What did I spend this week?</b><ScanLine className="size-4 text-[#C96632]" /></div><div className="journal-note journal-note-b"><span className="eyebrow text-[#4D7869]">Tax</span><b>Old or new regime?</b><ReceiptIndianRupee className="size-4 text-[#4D7869]" /></div><div className="journal-note journal-note-c"><span className="eyebrow text-[#A46C1E]">Family</span><b>Where should we begin?</b><HeartHandshake className="size-4 text-[#A46C1E]" /></div></div>;
}
