/* Week Comes Together: shared navigation makes the real Kubear web app and Android download the clear, consistent next actions on every route. */
import { ArrowUpRight, Menu, MoveRight, Smartphone } from "lucide-react";
import { Link, useLocation } from "wouter";
import { MotionObserver } from "@/components/MotionObserver";

const APP_URL = "https://kubear.kuberos.in";
const PLAY_URL = "https://play.google.com/store/apps/details?id=in.kuberos.kubear&pcampaignid=web_share";
const navItems = [
  { href: "/how-it-works", label: "How it works" },
  { href: "/your-money-picture", label: "Your money" },
  { href: "/privacy-data", label: "Privacy" },
  { href: "/journal", label: "Learn" },
  { href: "/tools", label: "Tools" },
];

function Mark() { return <img src="/manus-storage/kubear-symbol-mark_f469077a.png" alt="" className="size-9 object-contain" />; }
export function Brand({ inverse = false }: { inverse?: boolean }) { return <Link href="/" className={`inline-flex items-center gap-2.5 font-semibold tracking-[-0.045em] ${inverse ? "text-[#FFF4E6]" : "text-[#14312E]"}`} aria-label="Kubear home"><span className={inverse ? "brightness-0 invert" : ""}><Mark /></span><span className="text-[1.3rem]">Kubear</span></Link>; }

export function Header() {
  const [location] = useLocation();
  return <header className="sticky top-0 z-50 border-b border-[#14312E]/10 bg-[#FFF4E6]/90 backdrop-blur-xl"><a href="#main-content" className="skip-link">Skip to main content</a><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-4 px-5 py-3.5 sm:px-8 lg:px-12"><Brand /><nav className="hidden items-center gap-1 lg:flex" aria-label="Primary navigation">{navItems.map((item) => <Link key={item.href} href={item.href} className={`nav-link ${location === item.href ? "is-active" : ""}`}>{item.label}</Link>)}</nav><div className="flex items-center gap-2"><a className="button button-orange hidden sm:inline-flex" href={APP_URL}>Open Kubear <ArrowUpRight className="size-4" /></a><details className="relative lg:hidden"><summary className="grid size-11 cursor-pointer place-items-center rounded-xl border border-[#14312E]/15 bg-[#FFFDF8] text-[#14312E] marker:content-none hover:bg-[#F0E0C9]" aria-label="Open navigation menu"><Menu className="size-5" /></summary><nav className="mobile-nav absolute right-0 mt-3 w-[min(20rem,calc(100vw-2.5rem))] rounded-2xl border border-[#14312E]/12 bg-[#FFFDF8] p-2 shadow-[0_22px_55px_rgba(9,43,39,0.16)]" aria-label="Mobile navigation">{navItems.map((item) => <Link key={item.href} href={item.href} className={`block rounded-xl px-4 py-3 text-sm font-semibold ${location === item.href ? "bg-[#14312E] text-[#FFF4E6]" : "text-[#14312E] hover:bg-[#F0E0C9]"}`}>{item.label}</Link>)}<a className="button button-orange mt-2 flex w-full justify-center" href={APP_URL}>Open Kubear <ArrowUpRight className="size-4" /></a><a className="mt-3 flex items-center justify-center gap-2 px-2 py-2 text-sm font-bold text-[#D4512C]" href={PLAY_URL} target="_blank" rel="noreferrer"><Smartphone className="size-4" />Get it on Google Play</a></nav></details></div></div></header>;
}

export function Footer() {
  return <footer className="bg-[#092B27] text-[#FFF4E6]"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-20"><div className="grid gap-12 lg:grid-cols-[1.15fr_1fr_1fr] lg:gap-16"><div><Brand inverse /><p className="mt-5 max-w-sm text-base leading-7 text-[#D8E2DC]">See income, spending, bills, goals and home money in one clear view.</p><div className="mt-7 flex flex-col items-start gap-3"><a className="inline-flex items-center gap-2 text-sm font-bold text-[#FFB18E] transition-transform hover:translate-x-1" href={APP_URL}>Open Kubear <MoveRight className="size-4" /></a><a className="inline-flex items-center gap-2 text-sm font-bold text-[#FFE7A4] transition-transform hover:translate-x-1" href={PLAY_URL} target="_blank" rel="noreferrer">Get it on Google Play <ArrowUpRight className="size-4" /></a></div></div><div className="grid grid-cols-2 gap-8"><div><p className="eyebrow text-[#FFE7A4]">Explore</p><div className="mt-4 grid gap-3 text-sm text-[#D8E2DC]"><Link href="/how-it-works" className="hover:text-white">How it works</Link><Link href="/your-money-picture" className="hover:text-white">Your money</Link><Link href="/journal" className="hover:text-white">Learn</Link><Link href="/tools" className="hover:text-white">Tools</Link></div></div><div><p className="eyebrow text-[#FFE7A4]">Trust</p><div className="mt-4 grid gap-3 text-sm text-[#D8E2DC]"><Link href="/privacy-data" className="hover:text-white">Privacy</Link><a href="https://www.kuberos.in/legal/terms" target="_blank" rel="noreferrer" className="hover:text-white">Terms</a><a href="https://www.kuberos.in/legal/delete-account" target="_blank" rel="noreferrer" className="hover:text-white">Delete account</a><a href="mailto:hello@kuberos.in" className="hover:text-white">hello@kuberos.in</a></div></div></div><div className="border-t border-white/15 pt-7 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><p className="eyebrow text-[#FFB18E]">Your week, in one view</p><p className="mt-4 font-serif text-3xl leading-tight text-white">Your money is already there. See it clearly.</p><a className="button button-light mt-6" href={APP_URL}>Use the web app <ArrowUpRight className="size-4" /></a></div></div><div className="mt-16 flex flex-col gap-2 border-t border-white/15 pt-6 text-xs text-[#AAB6AE] sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Kuberos Technologies. Made in India.</span><span>Preview redesign. Final product details need owner approval.</span></div></div></footer>;
}

export function SiteLayout({ children }: { children: React.ReactNode }) { return <><Header /><MotionObserver /><main id="main-content">{children}</main><Footer /></>; }
